name: dirsrv-389ds
namespace: dirsrv-389ds
release:
  chart: chartmuseum/dirsrv-389ds:0.1.38
  version: 0.1.38
configuration:
  clusterDomain: cluster.local
  directorySuffix: dc=cluster,dc=local
secrets:
- secret-admin-username
- secret-admin-password
- secret-manager-password
