name: openvpn
namespace: openvpn
release:
  chart: chartmuseum/openvpn:0.1.247
  version: 0.1.247
configuration:
  gitBranch: master
  clusterDomain: cluster.local
  directorySuffix: "dc=cluster,dc=local"
